services:
  db:
    volumes:
      - pg_data:/var/lib/postgresql/data
      - /dev/null:/docker-entrypoint-initdb.d/01_schema.sql
      - /dev/null:/docker-entrypoint-initdb.d/02_seed.sql
      - ${DUMP_FILE:-./backEnd/dump.sql}:/docker-entrypoint-initdb.d/03_dump.sql

volumes:
  pg_data:
