FROM python:3.9-slim-bullseye

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend.py .

ENV POSTGRES_HOST=db
ENV POSTGRES_PORT=5432

EXPOSE 8080
CMD ["python", "backend.py"]
